#!/usr/bin/env python3
"""
Build the embedded texture atlas for the InfiniteMenu work sphere.

Why this exists
---------------
Opening index.html straight off disk (file://) makes every local image an opaque
origin. Drawing one into a canvas taints it, so WebGL refuses the texture upload
("Tainted canvases may not be loaded") and the section falls back to a flat grid.

Images loaded from a data: URL are NOT cross-origin, so a single embedded atlas
sidesteps the taint completely. It is written to its own script file so a real
host never downloads it: js/infinite-menu.js only injects that script after a
texture upload has actually been refused.

Layout must match the runtime atlas: `ceil(sqrt(n))` square cells, row-major,
each image cover-cropped into its cell. The runtime default for 16 items is a
4x4 grid of 512px cells = 2048x2048.

Usage
-----
    python tools/build-menu-atlas.py

Re-run after editing InfiniteMenu.SITE_ITEMS so the offline atlas matches.
"""

import base64
import io
import math
import os
import re
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  python -m pip install pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_JS = os.path.join(ROOT, "js", "infinite-menu.js")
OUT_JPG = os.path.join(ROOT, "assets", "infinite-menu-atlas.jpg")
OUT_JS = os.path.join(ROOT, "js", "infinite-menu-atlas.js")

CELL = 512
QUALITY = 72
BACKDROP = (0, 0, 0)             # matches data-background-color on the section


def read_items():
    """Pull the SITE_ITEMS image paths in order, so the atlas cannot drift."""
    src = open(SOURCE_JS, encoding="utf-8").read()
    block = re.search(r"InfiniteMenu\.SITE_ITEMS\s*=\s*\[(.*?)\n  \];", src, re.S)
    if not block:
        sys.exit("could not find InfiniteMenu.SITE_ITEMS in js/infinite-menu.js")
    paths = re.findall(r'image:\s*"([^"]+)"', block.group(1))
    if not paths:
        sys.exit("SITE_ITEMS has no image entries")
    return paths


def cover(img, size):
    """Cover-crop to a square, the same maths the runtime atlas uses."""
    w, h = img.size
    k = max(size / w, size / h)
    new = (max(size, int(round(w * k))), max(size, int(round(h * k))))
    img = img.resize(new, Image.LANCZOS)
    left = (img.width - size) // 2
    top = (img.height - size) // 2
    return img.crop((left, top, left + size, top + size))


def main():
    paths = read_items()
    n = len(paths)
    atlas_size = int(math.ceil(math.sqrt(n)))
    side = atlas_size * CELL
    print("items: %d -> atlas %dx%d cells of %dpx = %dx%d"
          % (n, atlas_size, atlas_size, CELL, side, side))

    sheet = Image.new("RGB", (side, side), BACKDROP)
    for i, rel in enumerate(paths):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        if not os.path.exists(path):
            sys.exit("missing image: %s" % rel)
        with Image.open(path) as img:
            img = img.convert("RGB")
            if img.width < CELL or img.height < CELL:
                print("  note: %s is %dx%d, upscaled to %d"
                      % (rel, img.width, img.height, CELL))
            cell = cover(img, CELL)
        sheet.paste(cell, ((i % atlas_size) * CELL, (i // atlas_size) * CELL))

    sheet.save(OUT_JPG, "JPEG", quality=QUALITY, optimize=True, progressive=True)
    raw = open(OUT_JPG, "rb").read()
    b64 = base64.b64encode(raw).decode("ascii")
    print("atlas jpg: %.0f KB  ->  base64 %.0f KB" % (len(raw) / 1024, len(b64) / 1024))

    header = (
        "/* Generated by tools/build-menu-atlas.py — do not edit by hand.\n"
        "   Pre-composited %dx%d atlas of the %d works in InfiniteMenu.SITE_ITEMS,\n"
        "   embedded as a data URL. It is only fetched when a WebGL texture upload\n"
        "   has been refused (i.e. the page is open over file://), because images\n"
        "   from a data: URL do not taint the canvas the way local files do. */\n"
        % (atlas_size, atlas_size, n)
    )
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("window.__infiniteMenuAtlas = { cells: %d, data: \"data:image/jpeg;base64,%s\" };\n"
                % (atlas_size, b64))
    print("wrote %s (%.0f KB)" % (os.path.relpath(OUT_JS, ROOT), os.path.getsize(OUT_JS) / 1024))


if __name__ == "__main__":
    main()
